[general]
import = ["alacritty-ext.toml"]
live_config_reload = true

[colors.bright]
black =   "#4C566A"
blue =    "#81A1C1"
cyan =    "#8FBCBB"
green =   "#A3BE8C"
magenta = "#B48EAD"
red =     "#BF616A"
white =   "#ECEFF4"
yellow =  "#EBCB8B"

[colors.normal]
black =   "#3B4252"
blue =    "#81A1C1"
cyan =    "#88C0D0"
green =   "#A3BE8C"
magenta = "#B48EAD"
red =     "#BF616A"
white =   "#E5E9F0"
yellow =  "#EBCB8B"

[font]
normal.family =       "JetBrainsMono Nerd Font Mono"
bold.family =         "JetBrainsMono Nerd Font Mono"
italic.family =       "JetBrainsMono Nerd Font Mono"
bold_italic.family =  "JetBrainsMono Nerd Font Mono"
size = 10.0

[window]
dynamic_padding = true
padding = { x = 10, y = 5 }
