require('nvim-treesitter.configs').setup {
  ensure_installed = {
    'angular',
    'bash',
    'clojure',
    'css',
    'csv',
    'diff',
    'dockerfile',
    'fennel',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'gomod',
    'helm',
    'html',
    'http',
    'java',
    'javascript',
    'json',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'markdown_inline',
    'properties',
    'python',
    'ruby',
    'scss',
    'sql',
    'terraform',
    'tmux',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml'
  },
  highlight = {
    enable = true,
  }
}
