# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# du
alias du='du -c -h'

# Git
alias gita='git add'
alias gitb='git branch'
alias gitbn='git checkout -b '
alias gitc='git commit -m '
alias gitca='git commit -a -m '
alias gitco='git checkout'
alias gitd='git diff'
alias gitl='git log -n 5'
alias gits='git status'
alias gitvd='git difftool'

# grep
alias grep='grep --color=auto'

# ls
if [[ "$(uname)" == "Darwin" ]]; then
    alias ls='ls -hG'
    alias ll='ls -lhaG'
else
    alias ls='ls -h --color'
    alias ll='ls --color -lha'
fi

# Subversion
alias svna='svn add'
alias svnc='svn commit --message '
alias svnd='svn diff'
alias svnl='svn log --limit 5'
alias svns='svn status'
alias svnu='svn update'

# Updates
alias update='sudo apt-get update && sudo apt-get upgrade -y'
