# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low --icon "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# du
alias du='du --total --human-readable'

# Git
alias gita='git add'
alias gitb='git branch'
alias gitbn='git checkout -b '
alias gitc='git commit --message '
alias gitca='git commit --all --message '
alias gitco='git checkout'
alias gitd='git diff'
alias gitl='git log --max-count 5'
alias gitp='git push'
alias gits='git status'
alias gitsf='git status | rev | cut --delimiter=" " --fields=1 | rev'
alias gitvd='git difftool'

# grep
if [ $(which rg) ]; then
  alias grep='rg'
else 
  alias grep='grep --color=auto'
fi

# ls
if [[ "$(uname)" == "Darwin" ]]; then
  alias ls='ls -hG'
  alias ll='ls -lhAG'
else
  alias ls='ls --human-readable --color'
  alias ll='ls --color --human-readable --almost-all -l'
fi

# NeoVim
if [ $(which nvim) ]; then
  alias vim='nvim'
fi

# Subversion
alias svna='svn add'
alias svnc='svn commit --message '
alias svnd='svn diff'
alias svnl='svn log --limit 5'
alias svns='svn status'
alias svnsf='svn status | rev | cut --delimiter=" " --fields=1 | rev'
alias svnu='svn update'

# Updates
alias update='sudo apt-get update && sudo apt-get upgrade -y'
